controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

add_pfe:
    path: /pfe/add/
    controller: App\Controller\PfeController::addPfe